# ************************************************************************
#  @author:     Andreas Kaeberlein
#  @copyright:  Copyright 2022
#  @credits:    AKAE
#
#  @license:    GPLv3
#  @maintainer: Andreas Kaeberlein
#  @email:      andreas.kaeberlein@web.de
#
#  @file:       unittest.yml
#  @date:       2022-08-10
#
#  @brief:      runs unit test
#
# ************************************************************************


name: texrefchk

on:
  push:
    paths-ignore:
      - 'doc/**'
      - 'README.md'
jobs:
  test:
    strategy:
      matrix:
        os: ['ubuntu-18.04', 'ubuntu-20.04', 'ubuntu-latest']
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: OS Version
        run: |
          cat /etc/os-release
      - name: texrefchk_pass_general
        run: |
          /bin/bash -c 'ret=$(./texrefchk.sh --texdir=./test/01_pass_general); \
                        if [ 0 -eq $? ]; then echo "[ PASS ]   test: 01_pass_general"; else [ FAIL ]   test: 01_pass_general; echo "$ret"; exit 1; fi; \
                       '
      - name: texrefchk_fail_general
        run: |
          /bin/bash -c 'ret=$(./texrefchk.sh --texdir=./test/10_fail_general); \
                        if [ 0 -ne $? ]; then echo "[ PASS ]   test: 10_fail_general"; else [ FAIL ]   test: 10_fail_general; echo "$ret"; exit 1; fi; \
                       '
      - name: texrefchk_fail_two_ref_one_line
        run: |
          /bin/bash -c 'ret=$(./texrefchk.sh --texdir=./test/11_fail_two_ref_one_line); \
                        if [ 0 -ne $? ]; then echo "[ PASS ]   test: 11_fail_two_ref_one_line"; else [ FAIL ]   test: 11_fail_two_ref_one_line; echo "$ret"; exit 1; fi; \
                       '
